package com.password.kg.model;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import com.password.kg.model.Passwords;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "PASSWORDS".
*/
public class PasswordsDao extends AbstractDao<Passwords, Long> {

    public static final String TABLENAME = "PASSWORDS";

    /**
     * Properties of entity Passwords.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Title = new Property(1, String.class, "Title", false, "TITLE");
        public final static Property Website = new Property(2, String.class, "Website", false, "WEBSITE");
        public final static Property Account = new Property(3, String.class, "Account", false, "ACCOUNT");
        public final static Property Password = new Property(4, String.class, "Password", false, "PASSWORD");
        public final static Property Description = new Property(5, String.class, "Description", false, "DESCRIPTION");
        public final static Property CategoryId = new Property(6, Long.class, "CategoryId", false, "CATEGORY_ID");
    };

    private DaoSession daoSession;

    private Query<Passwords> categories_PasswordsQuery;

    public PasswordsDao(DaoConfig config) {
        super(config);
    }
    
    public PasswordsDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"PASSWORDS\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"TITLE\" TEXT NOT NULL ," + // 1: Title
                "\"WEBSITE\" TEXT," + // 2: Website
                "\"ACCOUNT\" TEXT NOT NULL ," + // 3: Account
                "\"PASSWORD\" TEXT NOT NULL ," + // 4: Password
                "\"DESCRIPTION\" TEXT," + // 5: Description
                "\"CATEGORY_ID\" INTEGER);"); // 6: CategoryId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"PASSWORDS\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Passwords entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getTitle());
 
        String Website = entity.getWebsite();
        if (Website != null) {
            stmt.bindString(3, Website);
        }
        stmt.bindString(4, entity.getAccount());
        stmt.bindString(5, entity.getPassword());
 
        String Description = entity.getDescription();
        if (Description != null) {
            stmt.bindString(6, Description);
        }
 
        Long CategoryId = entity.getCategoryId();
        if (CategoryId != null) {
            stmt.bindLong(7, CategoryId);
        }
    }

    @Override
    protected void attachEntity(Passwords entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Passwords readEntity(Cursor cursor, int offset) {
        Passwords entity = new Passwords( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // Title
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // Website
            cursor.getString(offset + 3), // Account
            cursor.getString(offset + 4), // Password
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // Description
            cursor.isNull(offset + 6) ? null : cursor.getLong(offset + 6) // CategoryId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Passwords entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setTitle(cursor.getString(offset + 1));
        entity.setWebsite(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setAccount(cursor.getString(offset + 3));
        entity.setPassword(cursor.getString(offset + 4));
        entity.setDescription(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setCategoryId(cursor.isNull(offset + 6) ? null : cursor.getLong(offset + 6));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Passwords entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Passwords entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "Passwords" to-many relationship of Categories. */
    public List<Passwords> _queryCategories_Passwords(Long CategoryId) {
        synchronized (this) {
            if (categories_PasswordsQuery == null) {
                QueryBuilder<Passwords> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.CategoryId.eq(null));
                categories_PasswordsQuery = queryBuilder.build();
            }
        }
        Query<Passwords> query = categories_PasswordsQuery.forCurrentThread();
        query.setParameter(0, CategoryId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getCategoriesDao().getAllColumns());
            builder.append(" FROM PASSWORDS T");
            builder.append(" LEFT JOIN CATEGORIES T0 ON T.\"CATEGORY_ID\"=T0.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Passwords loadCurrentDeep(Cursor cursor, boolean lock) {
        Passwords entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Categories categories = loadCurrentOther(daoSession.getCategoriesDao(), cursor, offset);
        entity.setCategories(categories);

        return entity;    
    }

    public Passwords loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Passwords> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Passwords> list = new ArrayList<Passwords>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Passwords> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Passwords> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
